# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab58b2eaca814d87837ea815af0ef1044031a97cab0005c52cce837b1e5754228e64ea5f613d28d5f7e28960bf41f23eb685e8dd46c63551d2174c28676fd25e

test:
  secret_key_base: 9c0b4ee5eb97a70d471bbdc45138f2313aa5866a86fe9fbac858cac2e8cac5516c8c0999853d5a1ca467c70203ffadcdfcda5493fb1f136f06edb0caa2a481ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
